swagger: "2.0"
info:
  version: 1.0.0
  title: $name$
schemes:
  - http
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
paths:
  /health:
    get:
      summary: |
        Check the health of the play application
      produces:
        - application/json; charset=utf-8
      responses:
        "200":
          description: The request has been accepted and the status of the running application has been returned
          schema:
            type: object
            properties:
              status:
                type: string
  

  /build-info:
    get:
      summary: Get the build info of the current instance of the play application
      produces:
        - application/json; charset=utf-8
      responses:
        "200":
          description: The request has been accepted and the version of the running application has been returned
          schema:
            type: object
            properties:
              builtAtMillis: 
                type: long
              name:
                type: string
              lastCommitSha: 
                type: string
              scalaVersion:
                type: string
              version:
                type: version
              sbtVersion: 
                type: string
              builtAtString:
                type: date-time

definitions:
  Error:
    required:
      - code
      - description
