# Docker Compose Definitions for Testing Environments
# - In general, we publicly expose service ports to the host environment
#   to facilitate integration testing.
# - Use this file as follows:
#   docker-compose -f docker/docker-compose.yml -f docker/docker-compose-testing.yml up
version: "2.1"

services:
  play:
    ports:
      - "9000:9000"
